# Generated by Django 3.1.7 on 2021-03-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=3000)),
                ('sent_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feedback',
            },
        ),
    ]
